pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('ACCESS_KEY')
        AWS_SECRET_ACCESS_KEY = credentials('SECRET_ACCESS_KEY')
    }

    stages {

        /* Begin Template
        stage('template'){
            steps{
                sh 'scripts'
            }
        }
        End template*/


        stage('Hardware - Terraform'){
            steps{
                //Call script here
                sh 'scripts/install_dependencies.sh'
                sh 'scrips/aws_cli_config.sh'
                sh 'scripts/terraform_testing_env.sh'
            }
        }

        stage('Software - Ansible'){
            steps{
                //Call script here
                sh 'scripts/ansible.sh'
            }
        }

        stage('Test software'){
            steps{
                //Call script here
                sh 'scripts/test_software.sh'
            }
        }

        stage('Dockerfy and artifact'){
            steps{
                //Call script here
                sh 'scripts/artifact.sh'
            }
        }

        stage('Deploy images'){
            steps{
                //Call script here
                sh 'scripts/testing_env_kubernetes_script.sh'
            }
        }
    }
}