pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('ACCESS_KEY')
        AWS_SECRET_ACCESS_KEY = credentials('SECRET_ACCESS_KEY')
        TF_VAR_DB_ROOT_PASSWORD = credentials('MYSQL_ROOT_PASSWORD')
        //DOCKER_USERNAME = credentials('DOCKER_USERNAME')
        //DOCKER_PASSWORD = credentials('DOCKER_PASSWORD')

    }

    stages {

        /* Begin Template
        stage('template'){
            steps{
                sh 'scripts'
            }
        }
        End template*/

/*

        stage('Test software'){
            steps{
                sh 'Jenkins/scripts/test_software.sh'
            }
        }
*/

        stage('Hardware - Terraform'){
            steps{
                sh 'Jenkins/scripts/terraform/install_terraform_dependencies.sh'
                sh 'Jenkins/scripts/aws_cli_config.sh'
                //sh 'Jenkins/scripts/terraform/terraform_destroy_testing_env.sh'
                sh 'Jenkins/scripts/terraform/terraform_testing_env.sh'
                sh 'Jenkins/scripts/terraform/terraform_testing_env.sh'
                sh 'Jenkins/scripts/terraform/terraform_output_env_vars.sh'
            }
        }



        stage('Database initialisation'){
            steps{
                //Call script here
                sh 'Jenkins/scripts/environments/test/database_login.sh'
            }
        }

        stage('Dockerfy and artifact'){
            steps{
                //Call script here
                sh 'Jenkins/scripts/docker/docker-install.sh'
                sh 'Jenkins/scripts/docker/artifact.sh'
            }
        }

        stage('Deploy images'){
            steps{
                //Call script here
                sh 'Jenkins/scripts/kubernetes/testing_env_kubernetes_script.sh'
                sh 'Jenkins/scripts/kubernetes/deploy_all_pods-test-env.sh'
            }
        }
    }
}